from typing import Dict, Optional, Tuple
import torch


def select_features(data: Dict[int, torch.Tensor],
                    dropout_prob: float,
                    generator: Optional[torch.Generator]
                    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Sample train and test tensors from data generated by an SCM. We write
            B for the batch dimension,
            N for the number of data points (rows) in each table,
            F for the number of features,
            D_i for the embedding dimension at node i.
        
        Parameters:
        -----------
            data : dict
                The value at key i is a tensor of shape (B, N, D_i).
            dropout_prob : float
                The probability to drop any given feature.
            
        Returns:
            X: tensor of shape (B, N, F)
            y: tensor of shape (B, N, 1)
        """
        # Build data tensor [B, N, F_total]
        data_tensor = torch.cat(list(data.values()), dim=2)
        feat_dim_total = data_tensor.shape[2]

        # Target selection
        target_feat = torch.randint(0, feat_dim_total - 1, (1,), generator=generator)
        target_values = data_tensor[:, :, target_feat].squeeze(-1)

        # Candidate (non-target) columns
        remaining_cols = [i for i in range(feat_dim_total) if i != target_feat]
        kept = []
        dropped = []
        for col in remaining_cols:
            if torch.rand(1, generator=generator) < dropout_prob:
                dropped.append(col)
            else:
                kept.append(col)
        # Ensure at least one feature kept
        if len(kept) == 0:
            kept = [0]
            # remove it from dropped list if present
            dropped = dropped[1:]
        
        X = data_tensor[:, :, kept]
        y = target_values
        
        # shuffle data
        B, N, F = X.shape
        perm_rows = torch.randperm(N, device=X.device, generator=generator)
        X = X[:, perm_rows, :]
        y = y[:, perm_rows]
        perm_cols = torch.randperm(F, device=X.device, generator=generator)
        X = X[:, :, perm_cols]

        return X, y