from typing import Any, Dict, Iterator
import torch
import networkx as nx
from torch.utils.data import DataLoader

from prior.mechanisms.base_mechanism import BaseMechanism
from prior.scm.noise_dist import MixedDist
from prior.scm.scm import SCM


class LinearDataLoader(DataLoader):
    """
    A very simple dataloader.
    It samples one of the three graphs on two vertices. All mechanisms are linear.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int, 
                 seed: int = 42):
        """
        Initialize a new dataloader as specified by the given configuration dicts.
        
        Parameters
        ----------
        num_steps : int
            The number of batches contained in this dataloader.
        batch_size : int
            The number of data tables contained in each batch.
        seed : int
            Fixes the rng so that this generator samples the same data every time.
        """
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        # prepare the three graphs this prior is based on
        g_1 = nx.DiGraph()
        g_1.add_nodes_from([0, 1])
        g_2 = nx.DiGraph()
        g_2.add_edges_from([(0, 1)])
        g_3 = nx.DiGraph()
        g_3.add_edges_from([(0, 1)])
        self.graphs = [g_1, g_2, g_3]
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        return iter(self.batch_function() for _ in range(self.num_steps))
    
    def batch_function(self):
        # sample graph
        graph_index = torch.randint(len(self.graphs), (1,), generator=self.generator).item()
        graph = self.graphs[int(graph_index)]
            
        # build SCM
        noise = {v: MixedDist(std=1.0) for v in graph.nodes()}
        mechanisms = {}
        for v in graph.nodes():
            mechanisms[v] = LinearMechanism(graph.in_degree(v), 1, self.batch_size)
        scm = SCM(graph, mechanisms, noise)
            
        # sample dataset parameters
        num_train_samples = 100
        num_test_samples = 100
        
        # sample data from SCM
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate(sample_shape)
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        full_data['x'] = data[0]
        full_data['y'] = data[1]
        full_data['target_y'] = data[1]
        full_data['single_eval_pos'] = num_train_samples
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(nx.to_numpy_array(graph)).to(data[0].dtype),
            'graph': graph,
            'graph_index': graph_index,
            'scm': scm,
        }
        return full_data
    

class LinearMechanism(BaseMechanism):
    def __init__(self, input_dim: int, node_dim: int, batch_size: int):
        super().__init__(input_dim=input_dim, node_dim=node_dim)
        
        self.input_dim = input_dim
        if input_dim > 0:
            self.w_1 = torch.randn(batch_size, 1, 1)
            self.w_2 = torch.randn(batch_size, 1, 1)

    def _forward(self, parents: torch.Tensor, eps: torch.Tensor) -> torch.Tensor:
        if self.input_dim > 0:
            return parents * self.w_1 + self.w_2 + eps
        else:
            return eps