from typing import Any, Dict, Iterator
import torch
from torch.utils.data import DataLoader

from prior.causal_graph.graph_builder import GraphBuilder
from prior.preprocessing.preprocessing import Preprocessor
from prior.scm.scm_builder import SCMBuilder
from prior.utils.hyperparameter_sampling import sample_parameters, build_samplers
from prior.utils.select_data import select_features


class ObservationalDataLoader(DataLoader):
    """
    This is a high level class collecting and putting together the ingredients needed for making a dataloader.
    It produces purely observational data in a format compatible with NanoTabPFN.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int, 
                 graph_config: Dict[str, Any],
                 scm_config: Dict[str, Any],
                 preprocessing_config: Dict[str, Any],
                 dataset_config: Dict[str, Any],
                 seed: int = 42):
        """
        Initialize a new dataloader as specified by the given configuration dicts.
        
        Parameters
        ----------
        num_steps : int
            The number of batches contained in this dataloader.
        batch_size : int
            The number of data tables contained in each batch.
        graph_config : dict
            Specifies hyperparameters for creating the causal graphs underlying the data generation process.
        scm_config : dict
            Specifies hyperparameters for constructing SCMs on a given graph.
        preprocessing_config : dict
            Specifies hyperparameters for processing sampled data.
        dataset_config : dict
            Specifies hyperparameters for aggregating data generated by an SCM into data tables.
        seed : int
            Makes the sampling of hyperparameters across the entire data generation process deterministic.
            Does not make sampling of data tables themselves deterministic.
        """
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        self.graph_config = graph_config
        self.scm_config = scm_config
        self.preprocessing_config = preprocessing_config
        self.dataset_config = dataset_config
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.scm_samplers = build_samplers(self.scm_config, "scm")
        self.preprocessing_samplers = build_samplers(self.preprocessing_config, "preprocessing")
        self.dataset_samplers = build_samplers(self.dataset_config, "dataset")
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        
        def batch_function():
            # sample graph
            graph_params = sample_parameters(self.graph_samplers, "graph", self.generator)
            graph_builder = GraphBuilder()
            graph = graph_builder.sample_ER_DAG(**graph_params)
            
            # sample SCM
            scm_params = sample_parameters(self.scm_samplers, "scm", self.generator)
            scm_builder = SCMBuilder(graph, **scm_params)
            scm = scm_builder.build()
            
            # sample dataset parameters
            dataset_params = sample_parameters(self.dataset_samplers, "dataset", self.generator)
            num_train_samples = dataset_params["number_train_samples_per_dataset"]
            num_test_samples = dataset_params["number_test_samples_per_dataset"]
        
            # sample data from SCM
            total_samples = num_train_samples + num_test_samples
            sample_shape = (self.batch_size, total_samples)
            scm.sample_noise(sample_shape)
            data = scm.propagate(sample_shape)
            X, y = select_features(data, dataset_params["dropout_prob"])
            
            # preprocessing
            preprocessing_params = sample_parameters(self.preprocessing_samplers, "preprocessing", self.generator)
            preprocessor = Preprocessor(**preprocessing_params)
            preprocessor.fit(X[:, :num_train_samples, :], y[: , :num_train_samples])
            X, y = preprocessor.process(X, y)
            
            # aggregate data in the format required by NanoTabPFN
            full_data = {}
            full_data['x'] = X
            full_data['y'] = y.unsqueeze(-1)
            full_data['single_eval_pos'] = num_train_samples
            return full_data
            
        return iter(batch_function() for _ in range(self.num_steps))