from tfmplayground.model import NanoTabPFNModel


prior_config = {
    
    "dataset_config": {
        # number of train samples per dataset
        # int
        "number_train_samples_per_dataset": {
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 10, "high": 50}
        },
        # number of test samples per dataset
        # can be fixed because architecture is agnostic to the number of test samples
        # int
        "number_test_samples_per_dataset": {  # number of test samples per dataset. Can be fixed because architecture is agnostic to the number of test samples.
            "value": 20
        },
        # probability of not including a feature generated by the SCM in the final dataset
        # float
        "dropout_prob": {
            "value": 0.0
        },
    },

    "graph_config": {
        # number of nodes in the causal graph
        # each node may contain several features
        # one of these will become the target, the others (if not dropped) features of the generated data
        # int
        "num_nodes": { 
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 5, "high": 10}
        },
        # probability that any two nodes in the causal graph are connected
        # float
        "edge_prob": {
            "distribution": "uniform",
            "distribution_parameters": {"low": 0.1, "high": 0.3}
        },
    },

    "scm_config": {    
        # number of features contained in each node
        # int
        "node_dim": {
            "value": 1
        },
        # number of hidden layers in MLP mechanisms
        # int, >= 0
        "mlp_num_hidden_layers": {
            "value": 0
        },
        # number of hidden units in each layer of an MLP mechanism
        # int
        "mlp_hidden_dim": {
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 8, "high": 32}
        },
        # the standard deviation of noise sampled at root nodes when propagating through the SCM
        # float
        "root_std": {
            "value": 1.0
        },
        # the standard deviation of noise sampled at non-root nodes when propagating through the SCM
        # float
        "non_root_std": {
            "value": 0.5
        },
    }
}


training_config = {
    # path to save the trained model to
    # str
    "saveweights": "nano_tab_pfn",
    
    # the model we are training
    # NanoTabPFNModel
    "model": NanoTabPFNModel(
        num_attention_heads=8,
        embedding_size=192,
        mlp_hidden_size=768,
        num_layers=6,
        num_outputs=1000,
    ),
    
    # batch size used during training
    # int
    "batchsize": 2,
    
    # number of gradients to accumulate before updating weights
    # int
    "accumulate": 1,
    
    # learning rate
    # float
    "lr": 1e-4,
    
    # number of data batches contained in each epoch
    # int
    "steps": 1000,
    
    # number of epochs to train for
    # int
    "epochs": 75,
    
    # number of data batches used to infer buckets for bar distribution
    # int
    "n_bardist_samples": 5000,
    
    # output directory for tensorboard and data visualization
    # str
    "output": "output",
}