prior_config = {
    
    "dataset_config": {
        # number of train samples per dataset
        # int
        "number_train_samples_per_dataset": {
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 50, "high": 500}
        },
        # number of test samples per dataset
        # can be fixed because architecture is agnostic to the number of test samples
        # int
        "number_test_samples_per_dataset": {  # number of test samples per dataset. Can be fixed because architecture is agnostic to the number of test samples.
            "value": 100
        },
        # probability of not including a feature generated by the SCM in the final dataset
        # float
        "dropout_prob": {
            "value": 0.1
        },
    },

    "graph_config": {
        # number of nodes in the causal graph
        # each node may contain several features
        # one of these will become the target, the others (if not dropped) features of the generated data
        # int
        "num_nodes": { 
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 5, "high": 10}
        },
        # probability that any two nodes in the causal graph are connected
        # float
        "edge_prob": {
            "value": 0.2,
        },
    },

    "scm_config": {    
        # probability of using XGBoost mechanism as opposed to MLP mechanism
        # float
        "xgboost_prob": {
            "value": 0.0
        },
        # number of features contained in each node
        # int
        "node_dim": {
            "value": 2
        },
        # number of hidden layers in MLP mechanisms
        # int, >= 0
        "mlp_num_hidden_layers": {
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 0, "high": 0}
        },
        # number of hidden units in each layer of an MLP mechanism
        # int
        "mlp_hidden_dim": {
            "distribution": "categorical",
            "distribution_parameters": {"choices": [8, 16, 32, 64]}
        },
        # number of hidden layers in XGBoost mechanisms
        # 0 is probably already good
        # int, >= 0
        "xgb_num_hidden_layers": {
            "value": 0
        },
        # number of hidden layers in XGBoost mechanisms
        # int
        "xgb_hidden_dim": {
            "distribution": "categorical",
            "distribution_parameters": {"choices": [16, 32, 64]}
        },
        # number of samples from a Gaussian used to fit the random XGBoost models
        # int
        "xgb_n_training_samples": {
            "distribution": "discrete_uniform",
            "distribution_parameters": {"low": 100, "high": 500}
        },
        # whether to add noise to the XGBoost mechanisms
        # bool
        "xgb_add_noise": {
            "value": True
        },
        # the standard deviation of noise sampled at root nodes when propagating through the SCM
        # float
        "root_std": {
            "value": 1.0
        },
        # the standard deviation of noise sampled at non-root nodes when propagating through the SCM
        # float
        "non_root_std": {
            "value": 0.1
        },
        # whether to use a fast SCM implementation (as opposed to doing additional checks)
        # bool
        "scm_fast": { 
            "value": True
        },
    }
}


training_config = {
    # path to save the trained model to
    # str
    "saveweights": "graph_pfn_weights.pth",
    
    # number of attention heads
    # int
    "heads": 6,
    
    # embedding size of the transformer model
    # int
    "embeddingsize": 192,
    
    # hidden size of the transformer model
    # int
    "hiddensize": 768,
    
    # number of transformer layers
    # int
    "layers": 6,
    
    # batch size used during training
    # int
    "batchsize": 2,
    
    # number of gradients to accumulate before updating weights
    # int
    "accumulate": 1,
    
    # learning rate
    # float
    "lr": 1e-4,
    
    # number of data batches contained in each epoch
    # int
    "steps": 1000,
    
    # number of epochs to train for
    # int
    "epochs": 100,
    
    # checkpoint from which to continue training
    # str | None
    "loadcheckpoint": None,
    
    # number of buckets for the bar distribution
    # int
    "n_buckets": 100,
    
    # number of data batches used to infer buckets for bar distribution
    # int
    "n_bardist_samples": 100,
    
    # output directory for tensorboard and data visualization
    # str
    "output": "output",
}