from typing import Any, Dict, Iterator
import torch
from torch.utils.data import DataLoader
import torch.distributions as dist
import networkx as nx
from dopfnprior.mechanisms.simple_mechanism import SimpleMechanism
from dopfnprior.utils.sampling import TorchDistributionSampler
from dopfnprior.scm.scm import SCM
from dopfnprior.causal_graph.graph_builder import GraphBuilder


class ObservationalDataLoader(DataLoader):
    """
    A simple dataloader with fixed graph, noise std and activations.
    Two components are sampled independently:
    a probabilistic causal graph and the SCM mechanisms.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int,
                 n_train_samples: int = 5,
                 n_test_samples: int = 1,
                 seed: int = 42):
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.n_train_samples = n_train_samples
        self.n_test_samples = n_test_samples
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        self.nodes = ['x0', 'x1', 'x2', 'y']
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        n = len(self.nodes)
        for _ in range(self.num_steps):
            prob_adj = torch.zeros((n, n))
            rows, cols = torch.triu_indices(n, n, offset=1)
            num_pairs = rows.shape[0]
            sums = torch.rand(num_pairs, generator=self.generator)
            splits = torch.rand(num_pairs, generator=self.generator)
            prob_adj[rows, cols] = sums * splits
            prob_adj[cols, rows] = sums * (1 - splits)
            graph = self.make_graph(prob_adj)
            yield self.batch_function(graph)
    
    def make_iter(self, prob_adj: torch.Tensor) -> Iterator[Dict[str, Any]]:
        """Generate data batches with a fixed probabilistic adjacency matrix."""
        for _ in range(self.num_steps):
            graph = self.make_graph(prob_adj)
            yield self.batch_function(graph)
    
    def make_graph(self, prob_adj: torch.Tensor) -> nx.DiGraph:
        """Sample a graph from the given probabilistic adjacency matrix."""
        graph = nx.DiGraph()
        graph.add_nodes_from(self.nodes)
        for i, u in enumerate(self.nodes):
            for j, v in enumerate(self.nodes):
                if torch.rand((1,), generator=self.generator).item() < prob_adj[i, j]:
                    graph.add_edge(u, v)
        # resample if the graph is not acyclic
        if not nx.is_directed_acyclic_graph(graph):
            return self.make_graph(prob_adj)
        return graph
    
    def batch_function(self, graph: nx.DiGraph):
        mechanisms = {v: SimpleMechanism(self.nodes, self.generator) for v in self.nodes}
        for v in self.nodes:
            mechanisms[v].activation._module[1] = torch.nn.Tanh()
        noise = {v: TorchDistributionSampler(dist.Normal(loc=0.0, scale=1.0)) for v in self.nodes}
        
        scm = SCM(graph, mechanisms, noise, self.generator)
            
        num_train_samples = self.n_train_samples
        num_test_samples = self.n_test_samples
        
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
        
        # resample if z-normalization results in extreme values
        bound = 5.0
        for v in data:
            train_data = data[v][:, :num_train_samples]
            mean = train_data.mean(dim=1, keepdim=True)
            std = train_data.std(dim=1, keepdim=True) + 1e-8
            z_data = (data[v] - mean) / std
            if (z_data.abs() > bound).any():
                return self.batch_function(graph)
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        adjacency_matrix = nx.to_numpy_array(graph, nodelist=self.nodes)
        data_type = data['y'].dtype
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(adjacency_matrix).to(data_type),
            'graph': graph,
            'scm': scm,
        }
        
        full_data['x'] = torch.stack([data[v] for v in self.nodes if v != 'y'], dim=2)
        full_data['y'] = data['y'].unsqueeze(-1)
        full_data['values'] = data
        full_data['target_y'] = full_data['y'] # required by the current NanoTabPFN train loop
        full_data['single_eval_pos'] = num_train_samples
        
        return full_data