from typing import Any, Dict, Iterator
import numpy as np
import torch
from torch.utils.data import DataLoader
import torch.distributions as dist
import networkx as nx
from dopfnprior.mechanisms.simple_mechanism import SimpleMechanism
from dopfnprior.utils.sampling import TorchDistributionSampler, build_samplers, sample_parameters
from dopfnprior.scm.scm import SCM


class ObservationalDataLoader(DataLoader):
    """
    A simple dataloader with fixed graph, noise std and activations.
    Two components are sampled independently:
    a probabilistic causal graph and the SCM mechanisms.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int,
                 prior_config: Dict[str, Any],
                 seed: int = 42):
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        
        
        self.prior_config = prior_config
        self.graph_config = prior_config["graph_config"]
        self.scm_config = prior_config["scm_config"]
        self.dataset_config = prior_config["dataset_config"]
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.scm_samplers = build_samplers(self.scm_config, "scm")
        
        self.n_train_samples = self.dataset_config["number_train_samples_per_dataset"]["value"]
        self.n_test_samples = self.dataset_config["number_test_samples_per_dataset"]["value"]
        
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        n_nodes = self.graph_config["num_nodes"]["value"]
        self.nodes = [f'x{i}' for i in range(n_nodes - 1)] + ['y']
        
        self.bucket_mids = prior_config["bucket_mids"]
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        counter = 0
        while counter < self.num_steps:
            prob_adj = self.sample_prob_adj()
            graph = self.make_graph(prob_adj)
            # skip if graph is no good
            if not nx.is_directed_acyclic_graph(graph) or graph.in_degree('y') == 0 and graph.out_degree('y') == 0:
                continue
            counter += 1
            yield self.batch_function(graph)
    
    def make_iter(self, prob_adj: torch.Tensor) -> Iterator[Dict[str, Any]]:
        """Generate data batches with a fixed probabilistic adjacency matrix."""
        for _ in range(self.num_steps):
            graph = self.make_graph(prob_adj)
            yield self.batch_function(graph)
            
    def sample_prob_adj(self) -> torch.Tensor:
        n = len(self.nodes)
        np_seed = int(torch.randint(0, 2**31, (1,), generator=self.generator).item())
        self.rng = np.random.default_rng(np_seed)
        perm = self.rng.permutation(n)
        graph_params = sample_parameters(self.graph_samplers, self.generator)
        edge_prob = graph_params["edge_prob"]
        adj = self.sample_edge_prob((n, n), edge_prob=edge_prob)
        adj = np.triu(adj, k=1)
        adj[perm[:, None], perm] = adj.copy()
        prob_adj = torch.from_numpy(adj).float()
        return prob_adj
            
    def sample_edge_prob(self, shape, edge_prob) -> np.ndarray:
        """Sample edge weights from a beta distribution."""
        # Get numpy generator from torch generator
        beta = 0.5
        alpha = (edge_prob * beta) / (1 - edge_prob) # mean of distribution is at self.edge_prob
        edge_prob = self.rng.beta(a=alpha, b=beta, size=shape)
        return edge_prob
    
    def make_graph(self, prob_adj: torch.Tensor) -> nx.DiGraph:
        """Sample a graph from the given probabilistic adjacency matrix."""
        graph = nx.DiGraph()
        graph.add_nodes_from(self.nodes)
        for i, u in enumerate(self.nodes):
            for j, v in enumerate(self.nodes):
                if torch.rand((1,), generator=self.generator).item() < prob_adj[i, j]:
                    graph.add_edge(u, v)
        return graph
    
    def batch_function(self, graph: nx.DiGraph):
        scm_params = sample_parameters(self.scm_samplers, self.generator)
        mechanisms = {v: SimpleMechanism(self.nodes, self.generator) for v in self.nodes}
        noise = {}
        for v in [v for v in self.nodes if graph.in_degree(v) == 0]:
            std = scm_params["root_std"]
            noise[v] = TorchDistributionSampler(dist.Normal(loc=0.0, scale=std))
        for v in [v for v in self.nodes if graph.in_degree(v) > 0]:
            std = scm_params["non_root_std"]
            noise[v] = TorchDistributionSampler(dist.Normal(loc=0.0, scale=std))
        
        scm = SCM(graph, mechanisms, noise)
            
        num_train_samples = self.n_train_samples
        num_test_samples = self.n_test_samples
        
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
        
        # resample if z-normalization results in extreme values
        bound = 5.0
        for v in data:
            train_data = data[v][:, :num_train_samples]
            mean = train_data.mean(dim=1, keepdim=True)
            std = train_data.std(dim=1, keepdim=True) + 1e-8
            z_data = (data[v] - mean) / std
            if (z_data.abs() > bound).any():
                return self.batch_function(graph)
            
        # rescale buckets to model scale
        train_y = data['y'][:, :num_train_samples]
        mean_y = train_y.mean(dim=1, keepdim=True)
        std_y = train_y.std(dim=1, keepdim=True) + 1e-8
        scaled_bucket_mids = self.bucket_mids.unsqueeze(0).to(mean_y.device) * std_y + mean_y
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        adjacency_matrix = nx.to_numpy_array(graph, nodelist=self.nodes)
        data_type = data['y'].dtype
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(adjacency_matrix).to(data_type),
            'graph': graph,
            'scm': scm,
        }
        
        full_data['x'] = torch.stack([data[v] for v in self.nodes if v != 'y'], dim=2)
        full_data['y'] = data['y'].unsqueeze(-1)
        full_data['values'] = data
        full_data['target_y'] = full_data['y'] # required by the current NanoTabPFN train loop
        full_data['single_eval_pos'] = num_train_samples
        
        if self.n_test_samples == 1:
            test_data = {v: data[v][:, num_train_samples:].item() for v in data}
            log_probs = scm.log_likelihood_batch(test_data, scaled_bucket_mids)
            probs = torch.exp(log_probs)
            full_data['probs'] = probs
        
        return full_data