from typing import Any, Dict, Iterator
import torch
from torch.utils.data import DataLoader
import torch.distributions as dist
import networkx as nx
from dopfnprior.mechanisms.simple_mechanism import SimpleMechanism
from dopfnprior.utils.sampling import TorchDistributionSampler
from dopfnprior.scm.scm import SCM
from dopfnprior.causal_graph.graph_builder import GraphBuilder


class ObservationalDataLoader(DataLoader):
    """
    A very simple dataloader with fixed graph, noise std and activations.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int,
                 fixed_graph: bool = False, 
                 seed: int = 42):
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.fixed_graph = fixed_graph
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        return iter(self.batch_function() for _ in range(self.num_steps))
    
    def batch_function(self):
        if self.fixed_graph:
            graph = nx.DiGraph()
            nodes = ['x0', 'x1', 'x2', 'x3', 'y']
            graph.add_nodes_from(nodes)
            edges = [
                ('x3', 'x2'),
                ('x3', 'y'),
                ('x2', 'x1'),
                ('y', 'x1'),
                ('x0', 'y')
            ]
            graph.add_edges_from(edges)
        else:
            graph_builder = GraphBuilder(5, 0.2, 0.0)
            graph = graph_builder.sample(self.generator)
        mechanisms = {v: SimpleMechanism(nodes, self.generator) for v in nodes}
        for v in nodes:
            mechanisms[v].activation._module[1] = torch.nn.ReLU()
        noise = {v: TorchDistributionSampler(dist.Normal(loc=0, scale=0.5)) for v in nodes}
        scm = SCM(graph, mechanisms, noise, self.generator)
            
        num_train_samples = 5
        num_test_samples = 5
        
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        adjacency_matrix = nx.to_numpy_array(graph, nodelist=nodes)
        data_type = data['y'].dtype
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(adjacency_matrix).to(data_type),
            'graph': graph,
            'scm': scm,
        }
        nodes.remove('y')
        full_data['x'] = torch.stack([data[v] for v in nodes], dim=2)
        full_data['y'] = data['y'].unsqueeze(-1)
        full_data['values'] = data
        full_data['target_y'] = full_data['y'] # required by the current NanoTabPFN train loop
        full_data['single_eval_pos'] = num_train_samples
        
        return full_data