from typing import Any, Dict, Iterator
import torch
from torch.utils.data import DataLoader
import torch.distributions as dist
import networkx as nx

from priors.graph_builder_probabilistic import GraphBuilder
from dopfnprior.mechanisms.simple_mechanism import SimpleMechanism
from dopfnprior.utils.sampling import sample_parameters, build_samplers
from dopfnprior.utils.sampling import TorchDistributionSampler
from dopfnprior.scm.scm import SCM



class ObservationalDataLoader(DataLoader):
    """
    A dataloader that creates two probabilistic DAGs.
    The first is used for sampling training data, the second for test data.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int, 
                 prior_config: Dict[str, Any],
                 seed: int = 42):
        """
        Initialize a new dataloader as specified by the given configuration dicts.
        
        Parameters
        ----------
        num_steps : int
            The number of batches contained in this dataloader.
        batch_size : int
            The number of data tables contained in each batch.
        prior_config : dict
            Specifies hyperparameters for the prior.
        seed : int
            Fixes the rng so that this generator samples the same data every time.
        """
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        self.prior_config = prior_config
        self.graph_config = prior_config["graph_config"]
        self.scm_config = prior_config["scm_config"]
        self.dataset_config = prior_config["dataset_config"]
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.scm_samplers = build_samplers(self.scm_config, "scm")
        self.dataset_samplers = build_samplers(self.dataset_config, "dataset")
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        for _ in range(self.num_steps):
            graph_params = sample_parameters(self.graph_samplers, self.generator)
            graph_builder = GraphBuilder(**graph_params)
            graph_test = graph_builder.sample(self.generator)
            graph_train = graph_builder.perturbate_graph(graph_test, self.generator)
            yield self.batch_function(graph_test, graph_train)
            
    def make_iter(self, graph_test: nx.DiGraph) -> Iterator[Dict[str, Any]]:
        """Generate data batches with a fixed test graph."""
        for _ in range(self.num_steps):
            graph_params = sample_parameters(self.graph_samplers, self.generator)
            graph_builder = GraphBuilder(**graph_params)
            graph_train = graph_builder.perturbate_graph(graph_test, self.generator)
            yield self.batch_function(graph_test, graph_train)
    
    def batch_function(self, graph_test: nx.DiGraph, graph_train: nx.DiGraph):
        # sample SCMs
        scm_params = sample_parameters(self.scm_samplers, self.generator)
        nodes = list(graph_train.nodes)
        mechanisms = {v: SimpleMechanism(nodes, self.generator) for v in nodes}
        noise = {}
        for v in [v for v in nodes if graph_train.in_degree(v) == 0]:
            std = scm_params["root_std"]
            noise[v] = TorchDistributionSampler(dist.Normal(loc=0.0, scale=std))
        for v in [v for v in nodes if graph_train.in_degree(v) > 0]:
            std = scm_params["non_root_std"]
            noise[v] = TorchDistributionSampler(dist.Normal(loc=0.0, scale=std))
        
        scm_test = SCM(graph_test, mechanisms, noise, self.generator)
        scm_train = SCM(graph_train, mechanisms, noise, self.generator)
            
        # sample dataset parameters
        dataset_params = sample_parameters(self.dataset_samplers, self.generator)
        num_train_samples = dataset_params["number_train_samples_per_dataset"]
        num_test_samples = dataset_params["number_test_samples_per_dataset"]
        
        # sample data from SCMs
        sample_shape_train = (self.batch_size, num_train_samples)
        scm_train.sample_noise(sample_shape_train, generator=self.generator)
        data_train = scm_train.propagate(generator=self.generator)
        sample_shape_test = (self.batch_size, num_test_samples)
        scm_test.sample_noise(sample_shape_test, generator=self.generator)
        data_test = scm_test.propagate(generator=self.generator)
        
        data = {v: torch.cat([data_train[v], data_test[v]], dim=1) for v in nodes}
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        full_data['x'] = torch.stack([data[v] for v in nodes if v != 'y'], dim=2)
        full_data['y'] = data['y'].unsqueeze(-1)
        full_data['target_y'] = full_data['y'] # required by the current NanoTabPFN train loop
        full_data['single_eval_pos'] = num_train_samples
        full_data['values'] = data
        full_data['values_test'] = data_test
        full_data['values_train'] = data_train
        
        adjacency_matrix = nx.to_numpy_array(graph_test, nodelist=nodes)
        data_type = full_data['x'].dtype
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(adjacency_matrix).to(data_type),
            'graph_test': graph_test,
            'scm_test': scm_test,
            'graph_train': graph_train,
            'scm_train': scm_train,
            'sampled_params': {"scm_params": scm_params, "dataset_params": dataset_params},
        }
        
        return full_data