from typing import Any, Dict, Iterator, List
import torch
import networkx as nx
from torch.utils.data import DataLoader
import torch.distributions as dist

from dopfnprior.mechanisms.base_mechanism import BaseMechanism
from dopfnprior.scm.scm import SCM
from dopfnprior.utils.sampling import TorchDistributionSampler


class LinearDataLoader(DataLoader):
    """
    A very simple dataloader.
    It samples one of the three graphs on two vertices. All mechanisms are linear.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int, 
                 graphs: List[nx.DiGraph],
                 seed: int = 42):
        """
        Initialize a new dataloader as specified by the given configuration dicts.
        
        Parameters
        ----------
        num_steps : int
            The number of batches contained in this dataloader.
        batch_size : int
            The number of data tables contained in each batch.
        graph : nx.DiGraph
            The list of possible graphs underlying the data generated by this generator.
        seed : int
            Fixes the rng so that this generator samples the same data every time.
        """
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        self.graphs = graphs
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        return iter(self.batch_function() for _ in range(self.num_steps))
    
    def batch_function(self):
        # sample graph
        graph_index = torch.randint(len(self.graphs), (1,), generator=self.generator).item()
        graph: nx.DiGraph = self.graphs[int(graph_index)]
            
        # build SCM
        noise = {v: TorchDistributionSampler(dist.Normal(loc=0.0, scale=1.0)) for v in graph.nodes() if graph.in_degree(v) == 0} | \
                {v: TorchDistributionSampler(dist.Normal(loc=0.0, scale=1.0)) for v in graph.nodes() if graph.in_degree(v) > 0}
        mechanisms = {}
        for v in graph.nodes():
            mechanisms[v] = LinearMechanism(graph.in_degree(v), 1, self.batch_size, generator=self.generator)
        scm = SCM(graph, mechanisms, noise)
            
        # sample dataset parameters
        num_train_samples = 10
        num_test_samples = 10
        
        # sample data from SCM
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate(sample_shape)
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        data_keys = list(data.keys())
        full_data['x'] = torch.concat([data[i] for i in data_keys[:-1]], dim=-1)
        full_data['y'] = data[data_keys[-1]]
        full_data['target_y'] = full_data['y']
        full_data['single_eval_pos'] = num_train_samples
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(nx.to_numpy_array(graph)).to(data[0].dtype),
            'graph': graph,
            'graph_index': graph_index,
            'scm': scm,
        }
        return full_data
    

class LinearMechanism(BaseMechanism):
    def __init__(self, input_dim: int, node_dim: int, batch_size: int, generator: torch.Generator):
        super().__init__(input_dim=input_dim, node_dim=node_dim)
        
        self.input_dim = input_dim
        if input_dim > 0:
            self.w_1 = torch.randn(batch_size, 1, 1, generator=generator)
            self.w_2 = torch.randn(batch_size, 1, 1, generator=generator)

    def _forward(self, parents: torch.Tensor, eps: torch.Tensor) -> torch.Tensor:
        if self.input_dim > 0:
            return parents * self.w_1 + self.w_2 + eps
        else:
            return eps