import math
from typing import Any, Dict, Iterator
from collections import Counter
import numpy as np
import torch
from torch.utils.data import DataLoader
import networkx as nx
from dopfnprior.scm.scm_builder import SCMBuilder
from dopfnprior.scm.scm import SCM
from dopfnprior.utils.sampling import build_samplers, sample_parameters


class ObservationalDataLoader(DataLoader):
    """
    A general class for observational dataloaders.
    Returns both datasets for training and the distribution of the targets (if training with cross-entropy loss).
    Also returns both the true underlying adjacency matrix of an SCM and the probabilistic adjacency matrix used to sample it.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int,
                 prior_config: Dict[str, Any],
                 seed: int = 42):
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        
        self.prior_config = prior_config
        self.graph_config = prior_config["graph_config"]
        self.noise_config = prior_config["noise_config"]
        self.dataset_config = prior_config["dataset_config"]
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.noise_samplers = build_samplers(self.noise_config, "noise")
        self.dataset_samplers = build_samplers(self.dataset_config, "dataset")
        
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        self.activations = prior_config["activations"]
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        counter = 0
        while counter < self.num_steps:
            prob_adj = self.sample_prob_adj()
            graph = self.make_graph(prob_adj)
            # skip if graph is no good
            if not self.is_valid_graph(graph):
                continue
            counter += 1
            yield self.batch_function(graph, prob_adj)
    
    def make_iter(self, prob_adj: torch.Tensor) -> Iterator[Dict[str, Any]]:
        """Generate data batches with a fixed probabilistic adjacency matrix."""
        counter = 0
        while counter < self.num_steps:
            graph = self.make_graph(prob_adj)
            # skip if graph is no good
            if not self.is_valid_graph(graph):
                continue
            counter += 1
            yield self.batch_function(graph, prob_adj)
            
    def is_valid_graph(self, graph: nx.DiGraph) -> bool:
        """Check if the given graph is a valid DAG with 'y' as the target node."""
        return nx.is_directed_acyclic_graph(graph) and not (graph.in_degree('y') == 0 and graph.out_degree('y') == 0)
            
    def sample_prob_adj(self) -> torch.Tensor:
        graph_params = sample_parameters(self.graph_samplers, self.generator)
        num_nodes = graph_params["num_nodes"]
        edge_prob = graph_params["edge_prob"]
        
        np_seed = int(torch.randint(0, 2**31, (1,), generator=self.generator).item())
        self.rng = np.random.default_rng(np_seed)
        perm = self.rng.permutation(num_nodes)
        graph_params = sample_parameters(self.graph_samplers, self.generator)
        edge_prob = graph_params["edge_prob"]
        adj = self.sample_edge_prob((num_nodes, num_nodes), edge_prob=edge_prob)
        adj = np.triu(adj, k=1)
        adj[perm[:, None], perm] = adj.copy()
        prob_adj = torch.from_numpy(adj).float()
        return prob_adj
            
    def sample_edge_prob(self, shape, edge_prob) -> np.ndarray:
        """Sample edge weights from a beta distribution."""
        # Get numpy generator from torch generator
        beta = 0.5
        alpha = (edge_prob * beta) / (1 - edge_prob) # mean of distribution is at edge_prob
        edge_prob = self.rng.beta(a=alpha, b=beta, size=shape)
        return edge_prob
    
    def make_graph(self, prob_adj: torch.Tensor) -> nx.DiGraph:
        """Sample a graph from the given probabilistic adjacency matrix."""
        num_nodes = prob_adj.shape[0]
        nodes = [f'x{i}' for i in range(num_nodes - 1)] + ['y']
        graph = nx.DiGraph()
        graph.add_nodes_from(nodes)
        for i, u in enumerate(nodes):
            for j, v in enumerate(nodes):
                if torch.rand((1,), generator=self.generator).item() < prob_adj[i, j]:
                    graph.add_edge(u, v)
        return graph
    
    def batch_function(self, graph: nx.DiGraph, prob_adj: torch.Tensor):
        # sample SCM
        activations = self.prior_config["activations"]
        root_std_dist, non_root_std_dist = self.noise_samplers["root_std_dist"], self.noise_samplers["non_root_std_dist"]
        scm_builder = SCMBuilder(graph, activations=activations, root_std_dist=root_std_dist, non_root_std_dist=non_root_std_dist)
        scm = scm_builder.sample(self.generator)
            
        # sample dataset parameters
        dataset_params = sample_parameters(self.dataset_samplers, self.generator)
        num_train_samples = dataset_params["number_train_samples_per_dataset"]
        num_test_samples = dataset_params["number_test_samples_per_dataset"]
        
        # sample data from SCM
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
            
        # aggregate data
        full_data = {}
        adjacency_matrix = nx.to_numpy_array(graph)
        data_type = data['y'].dtype
        full_data['graph_information'] = {
            'adj': torch.from_numpy(adjacency_matrix).to(data_type),
            'prob_adj': prob_adj,
            'graph': graph,
            'scm': scm,
        }
        full_data['x'] = torch.stack([data[v] for v in graph.nodes if v != 'y'], dim=2)
        full_data['y'] = data['y']
        full_data['values'] = data
        full_data['single_eval_pos'] = num_train_samples
        full_data['data'] = data
        
        return full_data
    
    def _make_statistics(self, steps):
        """Sample a large number of SCMs from `self` to estimate densities of DAGs and noise."""
        print("Computing prior statistics...")
        graph_counts = Counter()
        for _ in range(steps):
            prob_adj = self.sample_prob_adj()
            graph = self.make_graph(prob_adj)
            if not self.is_valid_graph(graph):
                continue
            # encode graph as pair (nodes, edges)
            graph_tuple = (tuple(graph.nodes()), tuple(graph.edges()))
            graph_counts[graph_tuple] += 1
        self.graph_counts = graph_counts
        
    def log_likelihood(self, scm: SCM):
        """
        Return the log likelihood of the given SCM under this prior, up to an additive constant.
        Since each mechanism is equally likely, this only takes into account DAG and noise.
        """
        if not hasattr(self, 'graph_counts'):
            self._make_statistics(steps=10000)
        graph_tuple = (tuple(scm.dag.nodes()), tuple(scm.dag.edges()))
        graph_count = self.graph_counts.get(graph_tuple, 1)
        graph_ll = math.log(graph_count)
        noise_ll = 0.0
        for v in scm.dag.nodes:
            std = scm.noise[v].std()
            if scm.dag.in_degree(v) == 0:
                noise_ll += self.noise_samplers["root_std_dist"].log_prob(torch.tensor(std)).item()
            else:
                noise_ll += self.noise_samplers["non_root_std_dist"].log_prob(torch.tensor(std)).item()
        return graph_ll + noise_ll