import math
from typing import Any, Dict, Iterator
from collections import Counter
import numpy as np
import torch
from torch.utils.data import DataLoader
import networkx as nx
from dopfnprior.scm.scm_builder import SCMBuilder
from dopfnprior.scm.scm import SCM
from dopfnprior.utils.sampling import build_samplers, sample_parameters


class ObservationalDataLoader(DataLoader):
    """
    A general class for observational dataloaders.
    Returns both datasets for training and the distribution of the targets (if training with cross-entropy loss).
    Also returns both the true underlying adjacency matrix of an SCM and the probabilistic adjacency matrix used to sample it.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int,
                 prior_config: Dict[str, Any],
                 seed: int = 42):
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        
        self.prior_config = prior_config
        self.graph_config = prior_config["graph_config"]
        self.scm_config = prior_config["scm_config"]
        self.dataset_config = prior_config["dataset_config"]
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.scm_samplers = build_samplers(self.scm_config, "scm")
        self.dataset_samplers = build_samplers(self.dataset_config, "dataset")
        
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        counter = 0
        while counter < self.num_steps:
            prob_adj = self.sample_prob_adj()
            graph = self.make_graph(prob_adj)
            # skip if graph is no good
            if not self.is_valid_graph(graph):
                continue
            counter += 1
            yield self.batch_function(graph, prob_adj)
    
    def make_iter(self, prob_adj: torch.Tensor) -> Iterator[Dict[str, Any]]:
        """Generate data batches with a fixed probabilistic adjacency matrix."""
        counter = 0
        while counter < self.num_steps:
            graph = self.make_graph(prob_adj)
            # skip if graph is no good
            if not self.is_valid_graph(graph):
                continue
            counter += 1
            yield self.batch_function(graph, prob_adj)
            
    def is_valid_graph(self, graph: nx.DiGraph) -> bool:
        """Check if the given graph is a valid DAG with 'y' as the target node."""
        return nx.is_directed_acyclic_graph(graph) and not (graph.in_degree('y') == 0 and graph.out_degree('y') == 0)
            
    def sample_prob_adj(self) -> torch.Tensor:
        graph_params = sample_parameters(self.graph_samplers, self.generator)
        self.num_nodes = graph_params["num_nodes"]
        self.edge_prob = graph_params["edge_prob"]
        self.prob_adj_mode = graph_params["prob_adj_mode"]
        
        np_seed = int(torch.randint(0, 2**31, (1,), generator=self.generator).item())
        rng = np.random.default_rng(np_seed)
        if self.prob_adj_mode == "binary":
            adj = rng.binomial(1, self.edge_prob, size=(self.num_nodes, self.num_nodes))
            adj = np.triu(adj, k=1)
            perm = rng.permutation(self.num_nodes)
            adj[perm[:, None], perm] = adj.copy()
            return torch.from_numpy(adj).float()

        beta = 0.5
        alpha = (self.edge_prob * beta) / (1 - self.edge_prob) # mean of distribution is at edge_prob
        edge_prob = rng.beta(a=alpha, b=beta, size=(self.num_nodes, self.num_nodes))
        adj = np.triu(edge_prob, k=1)
        # split the probability mass between i -> j and j -> i
        shares = rng.random(size=(self.num_nodes, self.num_nodes))
        adj = adj * shares + adj.T * (1 - shares.T)
        perm = rng.permutation(self.num_nodes)
        adj[perm[:, None], perm] = adj.copy()
        
        if self.prob_adj_mode == "beta":
            return torch.from_numpy(adj).float()
        
        elif self.prob_adj_mode == "uncertain":
            # mix the beta matrix with a constant matrix at edge_prob, with random mixing weight
            mix_weight = 0.5
            adj = np.where(rng.random(size=adj.shape) < mix_weight, adj, self.edge_prob / 2)
            np.fill_diagonal(adj, 0)
            return torch.from_numpy(adj).float()
        else:
            raise ValueError(f"Invalid prob_adj_mode: {self.prob_adj_mode}")

    
    def make_graph(self, prob_adj: torch.Tensor) -> nx.DiGraph:
        """Sample a graph from the given probabilistic adjacency matrix."""
        num_nodes = prob_adj.shape[0]
        nodes = [f'x{i}' for i in range(num_nodes - 1)] + ['y']
        graph = nx.DiGraph()
        graph.add_nodes_from(nodes)
        for i in range(num_nodes):
            for j in range(i + 1, num_nodes):
                u, v = nodes[i], nodes[j]
                p_ij = prob_adj[i, j].item()
                p_ji = prob_adj[j, i].item()
                r = torch.rand((1,), generator=self.generator).item()
                if r < p_ij:
                    graph.add_edge(u, v)
                elif r < p_ij + p_ji:
                    graph.add_edge(v, u)
        return graph
    
    def batch_function(self, graph: nx.DiGraph, prob_adj: torch.Tensor):
        # sample SCM
        root_std_dist, non_root_std_dist = self.scm_samplers["root_std_dist"], self.scm_samplers["non_root_std_dist"]
        scm_builder = SCMBuilder(graph, 
                                 activation_dist=self.scm_samplers["activation_dist"], 
                                 root_std_dist=root_std_dist, 
                                 non_root_std_dist=non_root_std_dist)
        scm = scm_builder.sample(self.generator)
            
        # sample dataset parameters
        dataset_params = sample_parameters(self.dataset_samplers, self.generator)
        num_train_samples = dataset_params["number_train_samples_per_dataset"]
        num_test_samples = dataset_params["number_test_samples_per_dataset"]
        
        # sample data from SCM
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
        
        # resample in case of extreme values after z-normalization
        for v in graph.nodes:
            train_data = data[v][:, :num_train_samples]
            mean = train_data.mean(dim=1, keepdim=True)
            std = train_data.std(dim=1, keepdim=True)
            z_scores = (data[v] - mean) / (std + 1e-8)
            if (z_scores.abs() > 5).any():
                return self.batch_function(graph, prob_adj)
            
        # convert features to categorical
        categorical_prob_dist = self.scm_samplers["categorical_prob"]
        num_categories_dist = self.scm_samplers["num_categories"]
        for v, tensor in data.items():
            if v == 'y': continue
            
            categorical_prob = categorical_prob_dist.sample(generator=self.generator)
            num_categories = num_categories_dist.sample(generator=self.generator)

            if torch.rand((1,), generator=self.generator).item() < categorical_prob:
                b, r, d = tensor.shape 
                flat_tensor = tensor.permute(0, 2, 1).reshape(-1, r) # (b*d, r)
                q = torch.linspace(0, 1, steps=num_categories + 1, device=tensor.device)[1:-1]
                # thresholds shape: (num_categories-1, b*d) -> transposed to (b*d, num_categories-1)
                thresholds = torch.quantile(flat_tensor, q, dim=1).transpose(0, 1)
                buckets = torch.searchsorted(thresholds, flat_tensor.contiguous()) # both inputs of leading dim b*d
                # shuffle
                label_map = torch.randperm(num_categories, device='cpu', generator=self.generator).to(tensor.device)
                shuffled_buckets = label_map[buckets] # (b*d, r)
                data[v] = shuffled_buckets.reshape(b, d, r).permute(0, 2, 1).float() # (b*d, r) -> (b, d, r) -> (b, r, d)
        
        # target data
        target_data = data['y'][:, :, 0].unsqueeze(-1) # shape (B, N, 1)
        data['y'] = data['y'][:, :, 1:]
            
        # aggregate data
        full_data = {}
        adjacency_matrix = nx.to_numpy_array(graph)
        data_type = data['y'].dtype
        sampled_params = {
            'num_nodes': self.num_nodes,
            'edge_prob': self.edge_prob,
            'number_train_samples_per_dataset': num_train_samples,
            'root_std': np.mean([scm.noise[v].std() for v in graph.nodes if graph.in_degree(v) == 0]),
            'non_root_std': np.mean([scm.noise[v].std() for v in graph.nodes if graph.in_degree(v) > 0])
        }
        full_data['graph_information'] = {
            'adj': torch.from_numpy(adjacency_matrix).to(data_type),
            'prob_adj': prob_adj,
            'graph': graph,
            'scm': scm,
            'sampled_params': sampled_params
        }
        full_data['x'] = torch.cat([data[v] for v in data.keys()], dim=2)  # shape (B, N, F)
        full_data['y'] = target_data
        full_data['values'] = data
        full_data['single_eval_pos'] = num_train_samples
        full_data['data'] = data
        
        return full_data
    
    def _make_statistics(self, steps):
        """Sample a large number of SCMs from `self` to estimate densities of DAGs."""
        graph_counts = Counter()
        for _ in range(steps):
            prob_adj = self.sample_prob_adj()
            graph = self.make_graph(prob_adj)
            if not self.is_valid_graph(graph):
                continue
            # encode graph as pair (nodes, edges)
            graph_tuple = (tuple(graph.nodes()), tuple(sorted(graph.edges())))
            graph_counts[graph_tuple] += 1
        self.graph_counts = graph_counts
        
    def log_likelihood(self, scm: SCM):
        """
        Return the log likelihood of the given SCM under this prior, up to an additive constant.
        Since each mechanism is equally likely, this only takes into account DAG and noise.
        """
        if not hasattr(self, 'graph_counts'):
            self._make_statistics(steps=10000)
        graph_tuple = (tuple(scm.dag.nodes()), tuple(sorted(scm.dag.edges())))
        graph_count = self.graph_counts.get(graph_tuple, 1)
        graph_ll = math.log(graph_count)
        noise_ll = 0.0
        for v in scm.dag.nodes:
            std = scm.noise[v].std()
            if scm.dag.in_degree(v) == 0:
                noise_ll += self.scm_samplers["root_std_dist"].log_prob(torch.tensor(std)).item()
            else:
                noise_ll += self.scm_samplers["non_root_std_dist"].log_prob(torch.tensor(std)).item()
        return graph_ll + noise_ll