import math
from typing import Any, Dict, Iterator
import torch
from torch.utils.data import DataLoader
import torch.distributions as dist
import networkx as nx
from scipy.integrate import quad
from scipy.stats import binom

from dopfnprior.causal_graph.graph_builder import GraphBuilder
from dopfnprior.scm.scm_builder import SCMBuilder
from dopfnprior.scm.scm import SCM
from dopfnprior.utils.sampling import sample_parameters, build_samplers, FixedSampler
from dopfnprior.utils.sampling import TorchDistributionSampler


class ObservationalDataLoader(DataLoader):
    """
    This is a high level class collecting and putting together the ingredients needed for making a dataloader.
    It produces purely observational data in a format compatible with NanoTabPFN.
    """
    def __init__(self,
                 num_steps: int,
                 batch_size: int, 
                 prior_config: Dict[str, Any],
                 seed: int = 42):
        """
        Initialize a new dataloader as specified by the given configuration dicts.
        
        Parameters
        ----------
        num_steps : int
            The number of batches contained in this dataloader.
        batch_size : int
            The number of data tables contained in each batch.
        prior_config : dict
            Specifies hyperparameters for the prior.
        seed : int
            Fixes the rng so that this generator samples the same data every time.
        """
        self.seed = seed
        self.num_steps: int = num_steps
        self.batch_size: int = batch_size
        self.generator = torch.Generator()
        self.generator.manual_seed(seed)
        
        self.prior_config = prior_config
        self.graph_config = prior_config["graph_config"]
        self.scm_config = prior_config["scm_config"]
        self.dataset_config = prior_config["dataset_config"]
        
        self.graph_samplers = build_samplers(self.graph_config, "graph")
        self.scm_samplers = build_samplers(self.scm_config, "scm")
        self.dataset_samplers = build_samplers(self.dataset_config, "dataset")
        
    def __len__(self) -> int:
        """Return the number of batches contained in this dataloader."""
        return self.num_steps

    def __iter__(self) -> Iterator[Dict[str, Any]]:
        """
        Specify the iterator underlying this dataloader.
        Each sampled data batch is generated by `batch_function` below.
        """
        return iter(self.batch_function() for _ in range(self.num_steps))
    
    def batch_function(self):
        # sample graph
        graph_params = sample_parameters(self.graph_samplers, self.generator)
        graph_builder = GraphBuilder(**graph_params)
        graph = graph_builder.sample(self.generator)
            
        # sample SCM
        scm_params = sample_parameters(self.scm_samplers, self.generator)
        scm_builder = SCMBuilder(graph, **scm_params)
        scm = scm_builder.sample(self.generator)
            
        # sample dataset parameters
        dataset_params = sample_parameters(self.dataset_samplers, self.generator)
        num_train_samples = dataset_params["number_train_samples_per_dataset"]
        num_test_samples = dataset_params["number_test_samples_per_dataset"]
        
        # sample data from SCM
        total_samples = num_train_samples + num_test_samples
        sample_shape = (self.batch_size, total_samples)
        scm.sample_noise(sample_shape, generator=self.generator)
        data = scm.propagate()
            
        # aggregate data in the format required by NanoTabPFN
        full_data = {}
        nodelist = [v for v in graph.nodes if not graph.nodes[v].get("hidden", False)]
        nodelist.remove('y')
        full_data['x'] = torch.stack([data[v] for v in nodelist], dim=2)
        full_data['y'] = data['y']
        full_data['target_y'] = full_data['y'] # required by the current NanoTabPFN train loop
        full_data['single_eval_pos'] = num_train_samples
        
        nodelist.append('y')
        adjacency_matrix = nx.to_numpy_array(graph, nodelist=nodelist)
        data_type = full_data['x'].dtype
        full_data['graph_information'] = {
            'adjacency_matrix': torch.from_numpy(adjacency_matrix).to(data_type),
            'graph': graph,
            'scm': scm,
            'sampled_params': {"graph_params": graph_params, "scm_params": scm_params, "dataset_params": dataset_params},
        }
        # p(graph, scm) = p(scm | graph) * p(graph)
        # p(scm | graph) = \int p(scm | graph, scm_params) * p(scm_params) d(scm_params)
        # p(graph) = \int p(graph | graph_params) * p(graph_params) d(graph_params)
        graph_prob = self.graph_log_prob(len(graph.nodes), len(graph.edges))
        graph_dropout_prob = self.graph_dropout_log_prob(len(graph.nodes), len([v for v in graph.nodes if graph.nodes[v].get("hidden", False)]))
        scm_prob = self.noise_log_prob(scm)
        log_prob = scm_prob + graph_prob + graph_dropout_prob
        full_data['log_prob'] = log_prob
        
        return full_data
    
    def graph_log_prob(self, n_nodes, n_edges) -> float:
        """Return the log probability of sampling a graph with the specified number of nodes and edges."""
        n_edges_total = n_nodes * (n_nodes - 1) // 2
        sampler = self.graph_samplers['edge_prob']
        if isinstance(sampler, FixedSampler):
            edge_prob = sampler.value
            prob = binom.pmf(n_edges, n_edges_total, edge_prob)
            return math.log(prob + 1e-12)
        def integrand(edge_prob):
            # adjust edge probability as in the graph builder
            edge_prob_min = 2 / (n_nodes ** 1.2)
            edge_prob = max(edge_prob_min, edge_prob)
            edge_prob_log_prob = sampler.log_prob(torch.tensor([edge_prob]))
            return binom.pmf(n_edges, n_edges_total, edge_prob) * math.exp(edge_prob_log_prob)
        integral, _ = quad(integrand, 0.0, 1.0)
        # print(f"Graph with {n_nodes} nodes and {n_edges} edges has log prob {math.log(integral + 1e-12)}")
        return math.log(integral + 1e-12)
    
    def graph_dropout_log_prob(self, n_nodes, n_hidden_nodes) -> float:
        """Return the log probability of sampling a graph with the specified number of visible nodes."""
        sampler = self.graph_samplers['dropout_prob']
        if isinstance(sampler, FixedSampler):
            dropout_prob = sampler.value
            prob = binom.pmf(n_hidden_nodes, n_nodes, dropout_prob)
            return math.log(prob + 1e-12)
        def integrand(dropout_prob):
            dropout_prob_log_prob = sampler.log_prob(torch.tensor([dropout_prob]))
            return binom.pmf(n_hidden_nodes, n_nodes, dropout_prob) * math.exp(dropout_prob_log_prob)
        integral, _ = quad(integrand, 0.0, 1.0)
        # print(f"Graph with {n_nodes} nodes and {n_hidden_nodes} hidden nodes has dropout log prob {math.log(integral + 1e-12)}")
        return math.log(integral + 1e-12)
    
    def noise_log_prob(self, scm: SCM) -> float:
        """Return the log probability of sampling the noise stds in the given SCM."""
        log_prob = 0.0
        for v in scm.dag.nodes:
            if scm._is_root[v]:
                sampler = self.scm_samplers['root_std']
                if isinstance(sampler, FixedSampler):
                    mean_std = sampler.value
                    noise_sampler = TorchDistributionSampler(dist.Exponential(rate=1/mean_std))
                    std = scm.noise[v].distribution.scale
                    log_prob += noise_sampler.log_prob(torch.tensor([std]))
                else:
                    def integrand(mean_std):
                        noise_sampler = TorchDistributionSampler(dist.Exponential(rate=1/mean_std))
                        std = scm.noise[v].distribution.scale
                        mean_std_log_prob = sampler.log_prob(torch.tensor([mean_std]))
                        return math.exp(noise_sampler.log_prob(std)) * math.exp(mean_std_log_prob)
                    integral, _ = quad(integrand, 0.0, 2.0)
                    log_prob += math.log(integral + 1e-12)
            else:
                sampler = self.scm_samplers['non_root_std']
                if isinstance(sampler, FixedSampler):
                    mean_std = sampler.value
                    noise_sampler = TorchDistributionSampler(dist.Exponential(rate=1/mean_std))
                    std = scm.noise[v].distribution.scale
                    log_prob += noise_sampler.log_prob(torch.tensor([std]))
                else:
                    def integrand(mean_std):
                        noise_sampler = TorchDistributionSampler(dist.Exponential(rate=1/mean_std))
                        std = scm.noise[v].distribution.scale
                        mean_std_log_prob = sampler.log_prob(torch.tensor([mean_std]))
                        return math.exp(noise_sampler.log_prob(std)) * math.exp(mean_std_log_prob)
                    integral, _ = quad(integrand, 0.0, 2.0)
                    log_prob += math.log(integral + 1e-12)
        return log_prob